### ISSUE TITLE
NameError in Project #30 Youtube video download

### ISSUE THREAD

**Issue by liuxx437** [ndleah/python-mini-project#51]
Error message received:
    Exception in Tkinter callback
    Traceback (most recent call last):
    File "C:\Users\liuw09\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
        return self.func(*args)
    File "c:\Users\liuw09\OneDrive - Abbott\Projects\Python\python-mini-project\Youtube_video_download\main.py", line 25, in Download
        video = url.streams.filter(file_extension=extension).first()
    NameError: name 'extension' is not defined

**Comment by Akhilbisht798** [comment]
hey, I have created a pull request regarding this issue.
Please check and review it.
